import type { Item } from "./types";

/** Relative dates so the mockup always shows dated items near "today" */
const today = new Date();
const iso = (d: Date) => d.toISOString().slice(0, 10);
const plus = (days: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return iso(d);
};

export const SEED_ITEMS: Item[] = [
  {
    id: "i1",
    title: "Sunset Playground at Willow Park",
    category: "playgrounds",
    kind: "evergreen",
    timeOfDay: ["morning", "afternoon"],
    cost: "free",
    location: "Willow Park, 4th Ave",
    notes: "Shaded structure, good for ages 3–9. Bring scooters.",
    addedBy: "mom",
    interestedBy: ["mom", "kid1", "kid2"],
  },
  {
    id: "i2",
    title: "County Spring Fair",
    category: "fairs",
    kind: "dated",
    date: plus(6),
    endDate: plus(8),
    timeOfDay: ["afternoon", "evening"],
    cost: "10to25",
    pricePerPerson: 18,
    location: "Fairgrounds, Hwy 9",
    notes: "Rides, livestock, fireworks Saturday at 9pm.",
    addedBy: "dad",
    interestedBy: ["dad", "kid1", "kid2", "grandma"],
  },
  {
    id: "i3",
    title: "Natural History Museum",
    category: "museums",
    kind: "evergreen",
    timeOfDay: ["afternoon"],
    cost: "under10",
    pricePerPerson: 8,
    location: "Downtown",
    notes: "Free first Sunday of the month.",
    addedBy: "mom",
    interestedBy: ["mom", "kid1", "grandma"],
  },
  {
    id: "i4",
    title: "Blueberry picking at Old Mill Farm",
    category: "daytrips",
    kind: "dated",
    date: plus(13),
    timeOfDay: ["morning"],
    cost: "under10",
    pricePerPerson: 7,
    location: "Old Mill Farm (45 min drive)",
    addedBy: "grandma",
    interestedBy: ["mom", "grandma", "kid2"],
  },
  {
    id: "i5",
    title: "Family movie night at the drive-in",
    category: "shows",
    kind: "dated",
    date: plus(2),
    timeOfDay: ["evening"],
    cost: "10to25",
    pricePerPerson: 12,
    location: "Starlight Drive-In",
    notes: "Double feature, gates at 7:30.",
    addedBy: "dad",
    interestedBy: ["dad", "mom", "kid1", "kid2"],
  },
  {
    id: "i6",
    title: "Paint Your Own Pottery",
    category: "arts",
    kind: "evergreen",
    timeOfDay: ["afternoon"],
    cost: "25to50",
    pricePerPerson: 32,
    location: "Mudroom Studio",
    addedBy: "mom",
    interestedBy: ["mom", "kid1"],
  },
  {
    id: "i7",
    title: "Farmers Market & Brunch",
    category: "dining",
    kind: "evergreen",
    timeOfDay: ["morning"],
    cost: "under10",
    pricePerPerson: 9,
    location: "Town Square (Sat only)",
    addedBy: "mom",
    interestedBy: ["mom", "dad", "grandma"],
  },
  {
    id: "i8",
    title: "Botanical Gardens Lantern Walk",
    category: "seasonal",
    kind: "dated",
    date: plus(18),
    endDate: plus(40),
    timeOfDay: ["evening"],
    cost: "10to25",
    pricePerPerson: 15,
    location: "Botanical Gardens",
    notes: "Sweater weather. Ticketed timed entry.",
    addedBy: "grandma",
    interestedBy: ["grandma", "mom", "kid2"],
  },
  {
    id: "i9",
    title: "Little League home opener",
    category: "sports",
    kind: "dated",
    date: plus(4),
    timeOfDay: ["afternoon"],
    cost: "free",
    location: "Riverside Field",
    addedBy: "dad",
    interestedBy: ["dad", "kid1"],
  },
  {
    id: "i10",
    title: "Lakeside trail loop",
    category: "parks",
    kind: "evergreen",
    timeOfDay: ["morning", "afternoon"],
    cost: "free",
    location: "Cedar Lake",
    notes: "2.4 mile flat loop, stroller-friendly.",
    addedBy: "dad",
    interestedBy: ["dad", "mom", "kid1", "kid2"],
  },
  {
    id: "i11",
    title: "Symphony Family Concert",
    category: "shows",
    kind: "dated",
    date: plus(23),
    timeOfDay: ["afternoon"],
    cost: "25to50",
    pricePerPerson: 28,
    location: "Civic Hall",
    notes: "Instrument petting zoo in lobby pre-show.",
    addedBy: "grandma",
    interestedBy: ["grandma", "kid1"],
  },
  {
    id: "i12",
    title: "Pizza & board game night",
    category: "dining",
    kind: "evergreen",
    timeOfDay: ["evening"],
    cost: "10to25",
    pricePerPerson: 14,
    location: "Home",
    addedBy: "kid1",
    interestedBy: ["mom", "dad", "kid1", "kid2"],
  },
  {
    id: "i13",
    title: "Pumpkin patch & hayride",
    category: "seasonal",
    kind: "evergreen",
    timeOfDay: ["morning", "afternoon"],
    cost: "under10",
    pricePerPerson: 6,
    location: "Harvest Hollow Farm",
    addedBy: "mom",
    interestedBy: ["mom", "dad", "kid1", "kid2", "grandma"],
  },
  {
    id: "i14",
    title: "Aquarium",
    category: "museums",
    kind: "evergreen",
    timeOfDay: ["allday"],
    cost: "25to50",
    pricePerPerson: 34,
    location: "Harbor Aquarium",
    addedBy: "kid2",
    interestedBy: ["kid1", "kid2", "mom"],
  },
  {
    id: "i15",
    title: "State park overnight camp",
    category: "daytrips",
    kind: "dated",
    date: plus(35),
    endDate: plus(36),
    timeOfDay: ["allday"],
    cost: "50plus",
    pricePerPerson: 55,
    location: "Pine Ridge State Park",
    notes: "Reserve site in advance. Bring s'mores fixings.",
    addedBy: "dad",
    interestedBy: ["dad", "mom", "kid1", "kid2"],
  },
  {
    id: "i16",
    title: "Ice cream walk",
    category: "dining",
    kind: "evergreen",
    timeOfDay: ["evening"],
    cost: "under10",
    pricePerPerson: 6,
    location: "Main St",
    addedBy: "kid2",
    interestedBy: ["kid1", "kid2", "dad", "grandma"],
  },
  {
    id: "i17",
    title: "Library Saturday storytime",
    category: "arts",
    kind: "evergreen",
    timeOfDay: ["morning"],
    cost: "free",
    location: "Central Library",
    addedBy: "mom",
    interestedBy: ["mom", "kid2"],
  },
  {
    id: "i18",
    title: "Beach day",
    category: "parks",
    kind: "dated",
    date: plus(10),
    timeOfDay: ["allday"],
    cost: "free",
    location: "Crescent Beach",
    addedBy: "mom",
    interestedBy: ["mom", "dad", "kid1", "kid2"],
  },
  {
    id: "i19",
    title: "Six Flags summer trip",
    category: "themeparks",
    kind: "dated",
    date: plus(28),
    timeOfDay: ["allday"],
    cost: "50plus",
    pricePerPerson: 85,
    location: "Six Flags",
    notes: "Season pass saves $$ if we go more than twice.",
    addedBy: "kid1",
    interestedBy: ["kid1", "kid2", "dad"],
  },
  {
    id: "i20",
    title: "Local amusement park afternoon",
    category: "themeparks",
    kind: "evergreen",
    timeOfDay: ["afternoon", "evening"],
    cost: "25to50",
    pricePerPerson: 38,
    location: "Adventureland",
    notes: "Wristbands cheaper after 5pm.",
    addedBy: "dad",
    interestedBy: ["dad", "kid1", "kid2", "mom"],
  },
];
