import type { DiscoverEvent } from "./types";

// Curated from a research pass (Sept 2026) across Enschede's own municipal/tourism
// sites, expat & club communities, and nearby NL/DE border towns. Dates reflect
// what was published at research time — annual events whose 2026 date had already
// passed are marked "recurring" with the usual month instead of a stale ISO date.
// Re-check sourceUrl before relying on exact times.

export const DISCOVER_EVENTS: DiscoverEvent[] = [
  // ---- Enschede: official / city / tourism ----
  {
    id: "gogbot-2026",
    title: "GOGBOT Festival — \"Manufactured Minds\"",
    blurb: "City-wide art, technology & music festival across venues in the center, happening this week. Family-friendly: partly. Daytime art and tech installations suit older kids; evening shows and music are more for adults.",
    category: "shows",
    familyFriendly: "partly",
    city: "Enschede",
    country: "NL",
    kind: "dated",
    date: "2026-09-17",
    endDate: "2026-09-20",
    cost: "10to25",
    sourceName: "GOGBOT",
    sourceUrl: "https://www.gogbot.nl/",
    language: "en",
  },
  {
    id: "democratie-nu-exhibition",
    title: "\"Democratie NU?\" exhibition",
    blurb: "New contemporary-art exhibition on democracy, made together with GOGBOT. Family-friendly: yes for older kids and teens; the themes will go over little ones' heads.",
    category: "museums",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "dated",
    date: "2026-09-17",
    endDate: "2027-02-14",
    cost: "10to25",
    location: "Rijksmuseum Twenthe",
    sourceName: "Rijksmuseum Twenthe",
    sourceUrl: "https://www.rijksmuseumtwenthe.nl/zien-en-doen/democratie-nu",
    language: "nl",
  },
  {
    id: "halloweenkermis-enschede",
    title: "Halloweenkermis Enschede",
    blurb: "60+ fairground rides and attractions in Volkspark — free to enter, pay per ride. Family-friendly: yes, though some Halloween-themed haunted rides can be too scary for small children.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "dated",
    date: "2026-10-17",
    endDate: "2026-10-25",
    cost: "free",
    location: "Volkspark, Enschede",
    sourceName: "Uit in Enschede",
    sourceUrl: "https://www.uitinenschede.nl/evenementen/halloweenkermis",
    language: "nl",
  },
  {
    id: "museumnacht-twente",
    title: "Museumnacht Twente",
    blurb: "One ticket, one night — hop between Enschede's museums after dark. Family-friendly: partly. It's a late-evening event aimed at adults, but older kids can join the early part.",
    category: "museums",
    familyFriendly: "partly",
    city: "Enschede",
    country: "NL",
    kind: "dated",
    date: "2026-11-07",
    cost: "10to25",
    sourceName: "Rijksmuseum Twenthe",
    sourceUrl: "https://www.rijksmuseumtwenthe.nl/zien-en-doen/museumnacht-2026",
    language: "nl",
  },
  {
    id: "zaterdagmarkt-enschede",
    title: "Zaterdagmarkt Enschede",
    blurb: "~150-stall Saturday market on Van Heekplein, one of the region's largest. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Saturday, 08:00–17:00, year-round",
    repeatWeekdays: ["sat"],
    cost: "free",
    location: "Van Heekplein, Enschede",
    sourceName: "Gemeente Enschede",
    sourceUrl: "https://www.enschede.nl/markt-in-enschede",
    language: "nl",
  },
  {
    id: "dinsdagmarkt-enschede",
    title: "Dinsdagmarkt (Tuesday Market)",
    blurb: "Weekday counterpart to the Saturday market, same square, general goods and fresh produce. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Tuesday, 08:00–17:00, year-round",
    repeatWeekdays: ["tue"],
    cost: "free",
    location: "Van Heekplein, Enschede",
    sourceName: "Gemeente Enschede",
    sourceUrl: "https://www.enschede.nl/markt-in-enschede",
    language: "nl",
  },
  {
    id: "zondagmarkt-enschede",
    title: "Zondagmarkt (Sunday Market)",
    blurb: "Free family-friendly Sunday market with a kids' square, secondhand stalls and a different theme most weeks.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["afternoon"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Sunday, 12:00–17:00, year-round",
    repeatWeekdays: ["sun"],
    cost: "free",
    location: "Van Heekplein, Enschede",
    sourceName: "Zondagmarkt Enschede",
    sourceUrl: "https://zondagmarktenschede.nl/",
    language: "nl",
  },
  {
    id: "curiosamarkt-van-heekplein",
    title: "Curiosamarkt (flea & antiques)",
    blurb: "Antiques, vinyl, books, home decor and vintage clothing — runs within the Sunday market on selected Sundays through the season. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["afternoon"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Select Sundays, 12:00–17:00: Sep 20 & 27, Oct 4/11/18/25, Nov 1/8/15/22/29, Dec 6/13/20/27 2026, Jan 3 2027",
    repeatDates: [
      "2026-09-20", "2026-09-27", "2026-10-04", "2026-10-11", "2026-10-18",
      "2026-10-25", "2026-11-01", "2026-11-08", "2026-11-15", "2026-11-22",
      "2026-11-29", "2026-12-06", "2026-12-13", "2026-12-20", "2026-12-27",
      "2027-01-03",
    ],
    cost: "free",
    location: "Van Heekplein, Enschede",
    sourceName: "Zondagmarkt Enschede",
    sourceUrl: "https://zondagmarktenschede.nl/curiosamarkt/",
    language: "nl",
  },
  {
    id: "woensdagmarkt-glanerbrug",
    title: "Woensdagmarkt Glanerbrug",
    blurb: "Small neighborhood market in the Glanerbrug district. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Enschede (Glanerbrug)",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Wednesday, 08:00–13:00, year-round",
    repeatWeekdays: ["wed"],
    cost: "free",
    location: "Schoolstraat, Glanerbrug, Enschede",
    sourceName: "Uw Marktspecialist",
    sourceUrl: "https://uwmarktspecialist.nl/markten/enschede/over-de-markten/",
    language: "nl",
  },
  {
    id: "donderdagmarkt-wesselerbrink",
    title: "Donderdagmarkt Wesselerbrink",
    blurb: "Small neighborhood market in the Wesselerbrink district (south Enschede). Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Thursday, 08:00–13:00, year-round",
    repeatWeekdays: ["thu"],
    cost: "free",
    location: "Wesselerbrink centrum, Enschede",
    sourceName: "Uw Marktspecialist",
    sourceUrl: "https://uwmarktspecialist.nl/markten/enschede/over-de-markten/",
    language: "nl",
  },
  {
    id: "vrijdagmarkt-lonneker",
    title: "Vrijdagmarkt Lonneker",
    blurb: "Small neighborhood market in the Lonneker village center. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["afternoon", "evening"],
    city: "Enschede (Lonneker)",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Friday, 12:00–18:00, year-round",
    repeatWeekdays: ["fri"],
    cost: "free",
    location: "Lonneker centrum, Enschede",
    sourceName: "Uw Marktspecialist",
    sourceUrl: "https://uwmarktspecialist.nl/markten/enschede/over-de-markten/",
    language: "nl",
  },
  {
    id: "vrijdagmarkt-boekelo",
    title: "Vrijdagmarkt Boekelo",
    blurb: "Small neighborhood market in the Boekelo village center. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Enschede (Boekelo)",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Friday, 08:00–13:00, year-round",
    repeatWeekdays: ["fri"],
    cost: "free",
    location: "Boekelo centrum, Enschede",
    sourceName: "Uw Marktspecialist",
    sourceUrl: "https://uwmarktspecialist.nl/markten/enschede/over-de-markten/",
    language: "nl",
  },
  {
    id: "biologische-boerenmarkt-enschede",
    title: "Biologische Boerenmarkt Enschede",
    blurb: "Organic farmers' market with fresh regional produce, bread and dairy. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Saturday, 08:00–17:00, year-round",
    repeatWeekdays: ["sat"],
    cost: "free",
    location: "Ei van Ko, Langestraat 24, Enschede",
    sourceName: "Alles Duurzaam",
    sourceUrl: "https://www.allesduurzaam.nl/verkooppunten/verkooppunten_item/t/biologische_boerenmarkt_enschede",
    language: "nl",
  },
  {
    id: "twentse-vlooienmarkt",
    title: "Twentse Vlooienmarkt",
    blurb: "Large organized flea market at the former Twenthe airfield — dozens of stalls of secondhand goods. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "3x/year — Easter weekend, early May & early September (2026: Apr 4 & 6, May 2–3, Sept 5–6), Sat–Sun 09:00–16:00",
    cost: "under10",
    location: "Vliegveld Twenthe, Enschede",
    sourceName: "Uit in Enschede",
    sourceUrl: "https://www.uitinenschede.nl/evenementen/twentse-vlooienmarkt",
    language: "nl",
  },
  {
    id: "langste-vlooienmarkt-nederland",
    title: "Langste Vlooienmarkt van Nederland",
    blurb: "\"The Netherlands' longest flea market\" on the old airfield taxiway — huge, with free parking. Family-friendly: yes, but it's big, so bring a buggy for little ones.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Annually mid-June and mid-August (2026: Jun 13–14, Aug 15–16), 09:00–16:00",
    cost: "under10",
    location: "Vliegveld Twenthe (Taxibaan), Enschede",
    sourceName: "Don Events",
    sourceUrl: "https://donevents.nl/product/langste-vlooienmarkt-van-nederland-vliegveld-twente-enschede-15-16-augustus-2026/",
    language: "nl",
  },
  {
    id: "winters-enschede",
    title: "Winters Enschede (Christmas markets)",
    blurb: "The city center turns into a Winter Wonderland: multiple small Christmas markets, lights, an illuminated Christmas tree and Twentse Ros on Van Heekplein. Family-friendly: yes.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "dated",
    date: "2026-11-26",
    endDate: "2027-01-04",
    cost: "free",
    location: "Binnenstad (city center), Enschede",
    sourceName: "Uit in Enschede",
    sourceUrl: "https://www.uitinenschede.nl/evenementen/winters-enschede",
    language: "nl",
  },
  {
    id: "go-planet-parc",
    title: "Go Planet Parc",
    blurb: "Indoor karting, laser tag, bowling, a Monkey Town play paradise and diving — good rainy-day fallback. Family-friendly: yes. Monkey Town suits little ones; karting and laser tag suit older kids.",
    category: "themeparks",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Open year-round — check site for hours",
    cost: "25to50",
    sourceName: "Visit Enschede",
    sourceUrl: "https://www.visit-enschede.com/go-planet-parc",
    language: "en",
  },
  {
    id: "concordia-enschede",
    title: "Concordia — film & theatre",
    blurb: "Arthouse cinema plus youth/family theatre and music-theatre at the Oude Markt. Family-friendly: yes for the youth and family shows; check each film or show for ages.",
    category: "shows",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Ongoing programme — check the agenda",
    cost: "10to25",
    location: "Oude Markt, Enschede",
    sourceName: "Concordia",
    sourceUrl: "https://www.concordia.nl/nl/agenda",
    language: "nl",
  },
  {
    id: "tetem-enschede",
    title: "TETEM art & tech space",
    blurb: "Hands-on digital-culture and maker space, family-friendly and often free to visit.",
    category: "arts",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Ongoing exhibitions & workshops — check the agenda",
    cost: "free",
    sourceName: "TETEM",
    sourceUrl: "https://tetem.nl/agenda/",
    language: "nl",
  },
  {
    id: "grolsch-summer-sounds",
    title: "Grolsch Summer Sounds",
    blurb: "Free open-air concerts on the historic Oude Markt, three Thursday evenings each summer. Family-friendly: yes for early evening; it gets busy and beery later on.",
    category: "shows",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Three Thursday evenings each July (2026 ran Jul 9/16/23)",
    cost: "free",
    location: "Oude Markt, Enschede",
    sourceName: "Visit Enschede",
    sourceUrl: "https://www.visit-enschede.com/events/grolsch-summer-sounds-enschede-live",
    language: "en",
  },
  {
    id: "bevrijdingsfestival-overijssel",
    title: "Bevrijdingsfestival Overijssel",
    blurb: "The region's big free Liberation Day festival with music and family activities. Family-friendly: yes during the day; evenings are crowded with a young-adult crowd.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "dated",
    date: "2027-05-05",
    cost: "free",
    sourceName: "Bevrijdingsfestival Overijssel",
    sourceUrl: "https://bevrijdingsfestivaloverijssel.nl/",
    language: "nl",
  },
  {
    id: "paaskermis-enschede",
    title: "Paaskermis Enschede (Easter Fair)",
    blurb: "Big spring funfair with ~60 attractions in Volkspark. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Annually around Easter (2026 ran Apr 4–12)",
    cost: "free",
    location: "Volkspark, Enschede",
    sourceName: "Kermis.nu",
    sourceUrl: "https://kermis.nu/kermis/35/enschede/paaskermis/",
    language: "nl",
  },
  {
    id: "koningsdag-enschede",
    title: "Koningsdag Enschede (King's Day)",
    blurb: "City-wide King's Day celebrations, kids' vrijmarkt (flea market) and live music. Family-friendly: yes, especially the morning kids' vrijmarkt; the afternoon gets rowdy in the center.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "dated",
    date: "2027-04-27",
    cost: "free",
    sourceName: "Visit Enschede",
    sourceUrl: "https://visitenschede.nl/events/summer",
    language: "en",
  },
  {
    id: "maker-festival-twente",
    title: "Maker Festival Twente",
    blurb: "Family maker-festival at TETEM: food tech, workshops, and Architects of Air walk-in sculptures. Family-friendly: yes.",
    category: "arts",
    familyFriendly: "yes",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Annually in early May (2026 ran May 7–10)",
    cost: "free",
    sourceName: "TETEM",
    sourceUrl: "https://tetem.nl/makerfestivaltwente/",
    language: "nl",
  },

  // ---- Enschede: expat / international / clubs ----
  {
    id: "enschede-social-group",
    title: "Enschede Social Group",
    blurb: "Mixed locals + internationals meetup for drinks, game nights and the occasional sporty activity. Family-friendly: no. It's an adults' social meetup.",
    category: "clubs",
    familyFriendly: "no",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Social drinks ~monthly (often Saturdays), plus occasional extra meetups",
    cost: "free",
    sourceName: "Meetup",
    sourceUrl: "https://www.meetup.com/enschede-social-group/",
    language: "en",
  },
  {
    id: "expat-meet-and-greet",
    title: "Expat Meet & Greet",
    blurb: "Casual monthly drop-in get-together for internationals in the Twente region — no registration needed. Family-friendly: no. It's an adults' drinks meetup.",
    category: "clubs",
    familyFriendly: "no",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Monthly drop-in — confirm current day on site",
    cost: "free",
    sourceName: "ICEast (Expat Center East Netherlands)",
    sourceUrl: "https://iceast.nl/nl/expat/",
    language: "en",
  },
  {
    id: "twente-toastmasters",
    title: "Twente Toastmasters",
    blurb: "Practice public speaking and leadership in English, guests welcome, online attendance possible. Family-friendly: no. It's an adult club.",
    category: "clubs",
    familyFriendly: "no",
    timeOfDay: ["evening"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "2nd & 4th Tuesday, 19:30",
    repeatDates: [
      "2026-09-22", "2026-10-13", "2026-10-27", "2026-11-10", "2026-11-24",
      "2026-12-08", "2026-12-22", "2027-01-12", "2027-01-26", "2027-02-09",
      "2027-02-23", "2027-03-09", "2027-03-23", "2027-04-13", "2027-04-27",
      "2027-05-11", "2027-05-25", "2027-06-08", "2027-06-22", "2027-07-13",
      "2027-07-27", "2027-08-10", "2027-08-24",
    ],
    cost: "free",
    location: "Molukkenstraat 90, Enschede",
    sourceName: "Toastmasters International",
    sourceUrl: "https://www.toastmasters.org/Find-a-Club/01838841-twente-toastmasters",
    language: "en",
  },
  {
    id: "order-of-the-dice",
    title: "Order of the Dice (board games)",
    blurb: "Weekly casual board-game meetup open to anyone, just buy your own drinks. Family-friendly: partly. It's mostly adults, but older kids who play board games are usually welcome with a parent.",
    category: "clubs",
    familyFriendly: "partly",
    timeOfDay: ["evening"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Tuesday, 20:00",
    repeatWeekdays: ["tue"],
    cost: "free",
    location: "Café De Vluchte, Oldenzaalsestraat, Enschede",
    sourceName: "BoardGameGeek forum",
    sourceUrl: "https://boardgamegeek.com/thread/2366515/bordspellen-lenen-oost-nederland",
    language: "en",
  },
  {
    id: "enschedd-gameday",
    title: "EnscheD&D GameDay",
    blurb: "Two-day collaborative D&D one-shot for all parties, run with the 2024 5.5e rules; a youth table (ages 12–16) may run on the Sunday if there's enough interest. Family-friendly: partly. The main tables are for adults, and there may be a youth table (ages 12–16) on the Sunday.",
    category: "clubs",
    familyFriendly: "partly",
    timeOfDay: ["afternoon"],
    city: "Enschede",
    country: "NL",
    kind: "dated",
    date: "2026-10-17",
    endDate: "2026-10-18",
    startTime: "12:00",
    endTime: "17:30",
    cost: "under10",
    pricePerPerson: 10,
    location: "'t Volbert, Anemoonstraat 20, Enschede",
    sourceName: "EnscheD&D",
    sourceUrl: "https://enschedend.nl/en/",
    language: "en",
  },
  {
    id: "play-tabletop-nights",
    title: "PLAY! Tabletop Nights",
    blurb: "Monthly drop-in tabletop night at Sickhouse with EnscheD&D — RPG tables, board games, miniature painting and playtesting; donation-based entry. Family-friendly: no. It's an adults' evening in a bar venue.",
    category: "clubs",
    familyFriendly: "no",
    timeOfDay: ["evening"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Monthly, 19:00–23:00 (optional dinner walk-in from 18:00)",
    repeatDates: ["2026-10-09", "2026-12-12"],
    startTime: "19:00",
    endTime: "23:00",
    cost: "free",
    location: "Sickhouse, Oldenzaalsestraat 128, Enschede",
    sourceName: "Sickhouse",
    sourceUrl: "https://www.sickhouse.nl/events",
    language: "en",
  },
  {
    id: "fanaat-open-saturdays",
    title: "Fanaat open Saturdays",
    blurb: "University of Twente's board-game association opens its game library to non-members a few Saturdays a year. Family-friendly: partly. It's student-run, but older kids who like board games will enjoy it.",
    category: "clubs",
    familyFriendly: "partly",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Roughly every 2 months, on a Saturday",
    cost: "under10",
    pricePerPerson: 3,
    location: "University of Twente campus",
    sourceName: "BoardGameGeek forum",
    sourceUrl: "https://boardgamegeek.com/thread/2366515/bordspellen-lenen-oost-nederland",
    language: "en",
  },
  {
    id: "taalcafe-enschede",
    title: "Taalcafé (Huis voor Taal en Meedoen)",
    blurb: "Practice conversational Dutch with volunteers and other learners — handy for settling in. Family-friendly: no. It's aimed at adult language learners.",
    category: "clubs",
    familyFriendly: "no",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Weekly drop-in — exact day on site",
    cost: "free",
    location: "BplusC library, Enschede",
    sourceName: "BplusC Taalhuis",
    sourceUrl: "https://www.bplusc.nl/taalhuis/nederlands-leren/oefenen-in-het-taalhuis.html",
    language: "nl",
  },
  {
    id: "icf-enschede-sunday-service",
    title: "ICF Enschede Sunday Service",
    blurb: "English-language church service led by students, aimed at international students and expats. Family-friendly: yes, families are welcome.",
    category: "clubs",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Sunday, 10:30–12:30",
    repeatWeekdays: ["sun"],
    cost: "free",
    location: "Prinseschool, Prinsestraat 10, Enschede",
    sourceName: "International Christian Fellowship Enschede",
    sourceUrl: "https://www.icf-enschede.nl/services",
    language: "en",
  },
  {
    id: "english-catholic-mass-enschede",
    title: "International (English) Catholic Mass",
    blurb: "English Mass mainly attended by international students, academics and young families. Family-friendly: yes, young families attend.",
    category: "clubs",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "1st, 3rd & 5th Sunday, 11:00",
    repeatDates: [
      "2026-09-20", "2026-10-04", "2026-10-18", "2026-11-01", "2026-11-15",
      "2026-11-29", "2026-12-06", "2026-12-20", "2027-01-03", "2027-01-17",
      "2027-01-31", "2027-02-07", "2027-02-21", "2027-03-07", "2027-03-21",
      "2027-04-04", "2027-04-18", "2027-05-02", "2027-05-16", "2027-05-30",
      "2027-06-06", "2027-06-20", "2027-07-04", "2027-07-18", "2027-08-01",
      "2027-08-15", "2027-08-29",
    ],
    cost: "free",
    location: "Sint-Jacobuskerk, Oude Markt 1, Enschede",
    sourceName: "Ariëns Katholieke Studenten Enschede",
    sourceUrl: "https://rksariens.blogspot.com/p/mass-in-english.html",
    language: "en",
  },
  {
    id: "esn-twente",
    title: "ESN Twente",
    blurb: "Erasmus Student Network chapter running trips and events for international students. Family-friendly: no. It's for international students.",
    category: "clubs",
    familyFriendly: "no",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Ongoing events through the academic year",
    cost: "free",
    sourceName: "ESN Twente",
    sourceUrl: "https://esntwente.nl/",
    language: "en",
  },
  {
    id: "sv-lonneker-chess",
    title: "SV Lonneker chess club",
    blurb: "Established local chess club with a youth programme and rapid-chess evenings. Family-friendly: yes. There's a youth programme.",
    category: "clubs",
    familyFriendly: "yes",
    timeOfDay: ["evening"],
    city: "Enschede (Lonneker)",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Friday evening",
    repeatWeekdays: ["fri"],
    cost: "under10",
    sourceName: "SV Lonneker",
    sourceUrl: "https://www.svlonneker.nl/",
    language: "nl",
  },
  {
    id: "schaakvereniging-park-stokhorst",
    title: "Schaakvereniging Park Stokhorst",
    blurb: "Weekly chess club night that opens with a beginners' lesson. Family-friendly: partly. It's a club evening, but the beginners' lesson suits older kids.",
    category: "clubs",
    familyFriendly: "partly",
    timeOfDay: ["evening"],
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Monday — beginners' lesson 19:15, club night 20:00–24:00",
    repeatWeekdays: ["mon"],
    cost: "under10",
    sourceName: "SV Park Stokhorst",
    sourceUrl: "https://www.svparkstokhorst.nl/",
    language: "nl",
  },
  {
    id: "language-exchange-enschede",
    title: "Language Exchange — Enschede",
    blurb: "Directory for finding an in-person language-exchange partner in Enschede. Family-friendly: no. It's for adults looking for a language partner.",
    category: "clubs",
    familyFriendly: "no",
    city: "Enschede",
    country: "NL",
    kind: "recurring",
    recurrence: "Ongoing, self-organized via the platform",
    cost: "free",
    sourceName: "My Language Exchange",
    sourceUrl: "https://www.mylanguageexchange.com/city/Enschede__Netherlands.asp",
    language: "en",
  },

  // ---- Nearby Dutch towns ----
  {
    id: "lambertuskermis-hengelo",
    title: "Lambertuskermis",
    blurb:
      "One of the largest fairs in the eastern Netherlands (~150,000 visitors) in the Hengelo city center. Open Wed–Thu 13:30–23:00, Fri 13:30–midnight, Sat 10:00–midnight, Sun 12:00–21:00. Family-friendly: yes, best in the daytime; late evenings get busy with teens and adults.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Hengelo",
    country: "NL",
    kind: "dated",
    date: "2026-09-16",
    endDate: "2026-09-20",
    cost: "free",
    sourceName: "Gemeente Hengelo",
    sourceUrl: "https://www.hengelo.nl/?id=12781",
    language: "nl",
  },
  {
    id: "oranjekermis-hengelo",
    title: "Oranjekermis",
    blurb: "Classic spring funfair in Hengelo with rides and stalls. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Hengelo",
    country: "NL",
    kind: "recurring",
    recurrence: "Annually late April–early May",
    cost: "free",
    sourceName: "Kermis.nu",
    sourceUrl: "https://kermis.nu/kermis/984/hengelo/oranjekermis/",
    language: "nl",
  },
  {
    id: "carnavalsoptocht-oldenzaal",
    title: "Grote Twentsche Carnavalsoptocht",
    blurb: "Large regional carnival parade through \"Kloëzenstad\" Oldenzaal, floats and costumed groups. Family-friendly: yes for the parade; the café parties afterwards are for adults.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Oldenzaal",
    country: "NL",
    kind: "dated",
    date: "2027-02-07",
    cost: "free",
    sourceName: "Optochtenkalender.nl",
    sourceUrl: "https://www.optochtenkalender.nl/nederland/overijssel/oldenzaal/oldenzaal/grote-optocht.html",
    language: "nl",
  },
  {
    id: "twickel-kasteeltuinen-delden",
    title: "Twickel Kasteeltuinen",
    blurb: "Historic castle gardens on the Twickel estate — walkable grounds, good for a family day trip. Open through Nov 1. Family-friendly: yes.",
    category: "daytrips",
    familyFriendly: "yes",
    city: "Delden",
    country: "NL",
    kind: "dated",
    date: "2026-04-01",
    endDate: "2026-11-01",
    recurrence: "Wed–Sun, 10:00–17:00 (closed Mon/Tue)",
    startTime: "10:00",
    endTime: "17:00",
    cost: "under10",
    sourceName: "Visit Twente",
    sourceUrl: "https://www.visittwente.nl/agenda-item/175382/twickel-kasteeltuinen/",
    language: "nl",
  },
  {
    id: "buurtspoorweg-autumn-steam-days",
    title: "Museum Buurtspoorweg — Autumn Steam Days",
    blurb: "Heritage steam train between Haaksbergen and Boekelo, autumn-themed rides and museum activities. Family-friendly: yes.",
    category: "daytrips",
    familyFriendly: "yes",
    city: "Haaksbergen",
    country: "NL",
    kind: "dated",
    date: "2026-10-17",
    endDate: "2026-10-18",
    cost: "10to25",
    sourceName: "Museum Buurtspoorweg",
    sourceUrl: "https://www.museumbuurtspoorweg.nl/overzicht2025/",
    language: "nl",
  },
  {
    id: "buurtspoorweg-sinterklaas-nov22",
    title: "Museum Buurtspoorweg — Sinterklaas rit (Nov 22)",
    blurb: "Sinterklaas-themed heritage steam train ride, popular with young kids. Family-friendly: yes, made for young kids.",
    category: "daytrips",
    familyFriendly: "yes",
    city: "Haaksbergen",
    country: "NL",
    kind: "dated",
    date: "2026-11-22",
    cost: "10to25",
    sourceName: "Museum Buurtspoorweg",
    sourceUrl: "https://www.museumbuurtspoorweg.nl/overzicht2025/",
    language: "nl",
  },
  {
    id: "buurtspoorweg-sinterklaas-nov29",
    title: "Museum Buurtspoorweg — Sinterklaas rit (Nov 29)",
    blurb: "Second Sinterklaas-themed heritage steam train ride date. Family-friendly: yes, made for young kids.",
    category: "daytrips",
    familyFriendly: "yes",
    city: "Haaksbergen",
    country: "NL",
    kind: "dated",
    date: "2026-11-29",
    cost: "10to25",
    sourceName: "Museum Buurtspoorweg",
    sourceUrl: "https://www.museumbuurtspoorweg.nl/overzicht2025/",
    language: "nl",
  },
  {
    id: "voorjaarskermis-almelo",
    title: "Voorjaarskermis Almelo",
    blurb: "Spring funfair at Rembrandtveld in Almelo. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Almelo",
    country: "NL",
    kind: "recurring",
    recurrence: "Annually late May",
    cost: "free",
    location: "Rembrandtveld, Almelo",
    sourceName: "Uit in Almelo",
    sourceUrl: "https://www.uitinalmelo.nl/agenda-item/178627/voorjaarskermis-almelo/",
    language: "nl",
  },
  {
    id: "centrumkermis-almelo",
    title: "Centrumkermis Almelo",
    blurb: "City-center fair with rides, food stalls and stage performances. Family-friendly: yes, best in the daytime.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Almelo",
    country: "NL",
    kind: "recurring",
    recurrence: "Annually early-to-mid September (2026 ran Sept 10–14)",
    cost: "free",
    sourceName: "Kermis Almelo",
    sourceUrl: "https://www.kermisalmelo.nl/programma/",
    language: "nl",
  },
  {
    id: "kermis-losser",
    title: "Kermis Losser",
    blurb: "Fair at the Grote Markt with rides and stalls. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Losser",
    country: "NL",
    kind: "dated",
    date: "2026-10-03",
    endDate: "2026-10-06",
    cost: "free",
    location: "Grote Markt, Losser",
    sourceName: "Hallo Losser",
    sourceUrl: "https://hallolosser.nl/agenda-uitgaan-evenementen/kermis-losser",
    language: "nl",
  },
  {
    id: "bruegheliaans-festijn-losser",
    title: "Bruegheliaans Festijn",
    blurb: "Medieval/Bruegel-themed street festival with music, dance, crafts and street theatre. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Losser",
    country: "NL",
    kind: "recurring",
    recurrence: "Annually mid-August",
    cost: "free",
    sourceName: "Bruegheliaans Festijn Losser",
    sourceUrl: "https://bruegheliaansfestijn.nl/",
    language: "nl",
  },
  {
    id: "melbuulndagen-borne",
    title: "Melbuul'ndagen",
    blurb: "5-day town festival with fair, street theatre, live music, kids' afternoons and an oldtimer car show. Family-friendly: yes, with dedicated kids' afternoons.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Borne",
    country: "NL",
    kind: "recurring",
    recurrence: "Annually late August",
    cost: "free",
    sourceName: "Melbuul'ndagen Borne",
    sourceUrl: "https://melbuulndagen.nl/",
    language: "nl",
  },
  {
    id: "kermis-rijssen",
    title: "Kermis Rijssen",
    blurb: "Fair at Europaplein/Walstraat in the Rijssen town center. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Rijssen",
    country: "NL",
    kind: "recurring",
    recurrence: "Annually mid-to-late August",
    cost: "free",
    sourceName: "Kermis.nu",
    sourceUrl: "https://kermis.nu/kermis/1553/rijssen/kermis/",
    language: "nl",
  },
  {
    id: "kerstmarkt-oldenzaal",
    title: "Kerstmarkt Oldenzaal",
    blurb: "Illuminated stalls and log cabins through the city center: handmade decorations, regional food, performances. Family-friendly: yes.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Oldenzaal",
    country: "NL",
    kind: "dated",
    date: "2026-12-12",
    endDate: "2026-12-13",
    cost: "free",
    sourceName: "MarktenMeer",
    sourceUrl: "https://marktenmeer.nl/markt/kerstmarkt-oldenzaal-2026/",
    language: "nl",
  },
  {
    id: "weekmarkt-goor",
    title: "Weekmarkt Goor",
    blurb: "Weekly market at De Höfte — low-key, recurring family outing. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Goor",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Friday, 08:00–12:30, year-round",
    repeatWeekdays: ["fri"],
    cost: "free",
    location: "De Höfte, Goor",
    sourceName: "Visit Hof van Twente",
    sourceUrl: "https://www.visithofvantwente.nl/evenementen-agenda/goor/markt/",
    language: "nl",
  },

  // ---- Nearby German border towns ----
  {
    id: "summerfeelings-gronau",
    title: "Summerfeelings Open Air",
    blurb: "Open-air pop/schlager music festival with mainstream headline acts — an easy day/evening trip. Family-friendly: partly. It's a concert crowd; fine for older kids with ear protection.",
    category: "shows",
    familyFriendly: "partly",
    city: "Gronau",
    country: "DE",
    kind: "recurring",
    recurrence: "Annually mid-August",
    cost: "50plus",
    sourceName: "Summerfeelings Gronau",
    sourceUrl: "https://www.summerfeelings-gronau.com/",
    language: "de",
  },
  {
    id: "weihnachtsmarkt-epe-gronau",
    title: "Weihnachtsmarkt Epe",
    blurb: "Small-town Christmas market in Gronau's Epe district, craft huts and entertainment for kids. Family-friendly: yes.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Gronau",
    country: "DE",
    kind: "dated",
    date: "2026-12-04",
    endDate: "2026-12-06",
    cost: "free",
    sourceName: "Gronau Inside",
    sourceUrl: "https://gronau-inside.de/veranstaltung/weihnachtsmarkt-in-epe-2026",
    language: "de",
  },
  {
    id: "ritterfestspiele-bad-bentheim",
    title: "Ritterfestspiele Schlosspark",
    blurb: "Medieval tent village at Bentheim Castle park with jousting tournaments and a torchlit finale — a hit with kids. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Bad Bentheim",
    country: "DE",
    kind: "recurring",
    recurrence: "Annually around late April/early May",
    cost: "10to25",
    pricePerPerson: 14,
    location: "Burg Bentheim, Bad Bentheim",
    sourceName: "mittelaltermarkt.online",
    sourceUrl: "https://mittelaltermarkt.online/event/21-ritterfestspiele-schlosspark-bad-bentheim-2026/",
    language: "de",
  },
  {
    id: "weihnachtsmarkt-bad-bentheim",
    title: "Bad Bentheimer Weihnachtsmarkt",
    blurb: "~60 stalls of handcrafted goods below the castle, with music — classic cosy German Christmas market. Family-friendly: yes.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Bad Bentheim",
    country: "DE",
    kind: "dated",
    date: "2026-12-04",
    endDate: "2026-12-06",
    cost: "free",
    sourceName: "Grafschaft Bentheim Tourismus",
    sourceUrl: "https://www.grafschaft-bentheim-tourismus.de/event/bad-bentheimer-weihnachtsmarkt",
    language: "de",
  },
  {
    id: "burg-bentheim-castle",
    title: "Burg Bentheim (castle)",
    blurb: "One of Germany's largest hilltop castles, with tours, a museum and seasonal events — a strong year-round day-trip anchor. Family-friendly: yes.",
    category: "daytrips",
    familyFriendly: "yes",
    city: "Bad Bentheim",
    country: "DE",
    kind: "recurring",
    recurrence: "Open year-round — check site for tours & seasonal events",
    cost: "under10",
    sourceName: "Stadt Bad Bentheim",
    sourceUrl: "https://www.badbentheim.de/veranstaltungen/veranstaltungskalender",
    language: "de",
  },
  {
    id: "tierpark-nordhorn",
    title: "Tierpark Nordhorn (zoo)",
    blurb: "\"Family zoo in the green\" with 2,500+ animals, adventure playgrounds and a lakeside setting. Family-friendly: yes.",
    category: "daytrips",
    familyFriendly: "yes",
    city: "Nordhorn",
    country: "DE",
    kind: "recurring",
    recurrence: "Open 365 days/year — hours vary by season",
    cost: "10to25",
    sourceName: "Tierpark Nordhorn",
    sourceUrl: "https://www.tierpark-nordhorn.de/",
    language: "de",
  },
  {
    id: "weihnachtsmarkt-vechtesee-nordhorn",
    title: "Weihnachtsmarkt am Vechtesee",
    blurb: "Indoor/covered Christmas market by the Vechtesee with ~35 craft stalls, waffles and mulled wine. Family-friendly: yes.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Nordhorn",
    country: "DE",
    kind: "dated",
    date: "2026-11-26",
    endDate: "2026-11-27",
    cost: "free",
    sourceName: "GN Online (Grafschafter Nachrichten)",
    sourceUrl: "https://www.gn-online.de/nordhorn/weihnachtsmarkt-im-wohnstift-am-vechtesee-14135.html",
    language: "de",
  },
  {
    id: "ochtrup-fruhjahrskirmes",
    title: "Ochtruper Frühjahrskirmes",
    blurb: "Classic four-day spring funfair on the Marktplatz — very close via Losser. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Ochtrup",
    country: "DE",
    kind: "recurring",
    recurrence: "Annually late April",
    cost: "free",
    sourceName: "Kirmesforum",
    sourceUrl: "https://www.kirmesforum.de/threads/ochtrup-48607-fr%C3%BChjahrskirmes-24-04-27-04-2026.78548/",
    language: "de",
  },
  {
    id: "ochtrup-herbstkirmes",
    title: "Ochtruper Herbstkirmes",
    blurb: "Autumn counterpart to the spring Kirmes, usually with a fireworks evening. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Ochtrup",
    country: "DE",
    kind: "recurring",
    recurrence: "Annually mid-August",
    cost: "free",
    sourceName: "trend-lokal.de",
    sourceUrl: "https://trend-lokal.de/event/ochtruper-herbstkirmes/",
    language: "de",
  },
  {
    id: "pottbackermarkt-ochtrup",
    title: "Pottbäckermarkt & Leinewebersonntag",
    blurb: "Historic crafts and textile-history market celebrating Ochtrup's weaving/pottery heritage, family programme. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    city: "Ochtrup",
    country: "DE",
    kind: "recurring",
    recurrence: "Annually in October — exact date TBC, check site",
    cost: "free",
    sourceName: "Münsterland.com",
    sourceUrl: "https://www.muensterland.com/en/tourism/orte-muensterland/places-in-munsterland/ochtrup/events-in-ochtrup/",
    language: "en",
  },
  {
    id: "herbstsend-munster",
    title: "Herbstsend",
    blurb: "One of Germany's oldest and biggest funfairs on Schlossplatz — a bigger outing, ~45-50 min away. Family-friendly: yes.",
    category: "fairs",
    familyFriendly: "yes",
    city: "Münster",
    country: "DE",
    kind: "dated",
    date: "2026-10-24",
    endDate: "2026-11-01",
    cost: "free",
    location: "Schlossplatz, Münster",
    sourceName: "Stadt Münster",
    sourceUrl: "https://www.stadt-muenster.de/send/startseite",
    language: "de",
  },
  {
    id: "weihnachtsmarkt-prinzipalmarkt-munster",
    title: "Weihnachtsmarkt Prinzipalmarkt",
    blurb: "~90 huts around the Gothic town hall, one of NRW's most-visited Christmas markets. Family-friendly: yes, but very crowded on weekend evenings, so go early with a buggy.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Münster",
    country: "DE",
    kind: "dated",
    date: "2026-11-23",
    endDate: "2026-12-23",
    cost: "free",
    location: "Prinzipalmarkt, Münster",
    sourceName: "Stadt Münster",
    sourceUrl: "https://www.stadt-muenster.de/weihnachtsmarkt/",
    language: "de",
  },
  {
    id: "emszauber-rheine",
    title: "Emszauber (winter market)",
    blurb: "Five-week riverside winter market on the Ems with mulled wine, food stalls and lights. Family-friendly: yes.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Rheine",
    country: "DE",
    kind: "dated",
    date: "2026-11-13",
    endDate: "2026-12-21",
    cost: "free",
    sourceName: "Emszauber (official)",
    sourceUrl: "https://www.emszauber.de/",
    language: "de",
  },
  {
    id: "emsfestival-rheine",
    title: "EmsFestival",
    blurb: "Riverside music festival with a floating stage on the Ems — a lively summer evening option. Family-friendly: partly. It's an evening music festival; fine for older kids.",
    category: "shows",
    familyFriendly: "partly",
    city: "Rheine",
    country: "DE",
    kind: "recurring",
    recurrence: "Annually late July",
    cost: "25to50",
    sourceName: "Rheine Tourismus",
    sourceUrl: "https://www.rheine-tourismus.de/events/monatliche-stadtfeste/emsfestival/index.html",
    language: "de",
  },
  {
    id: "nikolausmarkt-rheine",
    title: "Nikolausmarkt",
    blurb: "Historic-square winter market with fire-roasted bread and straw-bale seating; St. Nicholas arrives by boat on the Ems. Family-friendly: yes.",
    category: "seasonal",
    familyFriendly: "yes",
    city: "Rheine",
    country: "DE",
    kind: "recurring",
    recurrence: "Early December (~4 days) — exact dates TBC, check site",
    cost: "free",
    sourceName: "Münsterland.com",
    sourceUrl: "https://www.muensterland.com/en/tourism/service/events/christmas-markets-in-munsterland/christmas-markets-rheine/",
    language: "en",
  },

  // ---- Nearby towns: regular weekly markets ----
  {
    id: "weekmarkt-hengelo",
    title: "Weekmarkt Hengelo",
    blurb: "General-goods market in the Hengelo town center, twice a week. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Hengelo",
    country: "NL",
    kind: "recurring",
    recurrence: "Wed & Sat, ~08:30–17:00 (temporarily relocates to De Wetstraat during carnival/festival weeks)",
    repeatWeekdays: ["wed", "sat"],
    cost: "free",
    location: "Marktplein, Hengelo",
    sourceName: "Uw Marktspecialist",
    sourceUrl: "https://uwmarktspecialist.nl/markten/markt/hengelo-ov/weekmarkt/woensdag/centrum-34/",
    language: "nl",
  },
  {
    id: "weekmarkt-almelo",
    title: "Weekmarkt Almelo",
    blurb: "Two weekly markets on the same square — a smaller Thursday one and a larger Saturday one. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Almelo",
    country: "NL",
    kind: "recurring",
    recurrence: "Thu 09:00–14:00 (smaller) & Sat 09:00–17:00 (larger)",
    repeatWeekdays: ["thu", "sat"],
    cost: "free",
    location: "Centrumplein, Almelo",
    sourceName: "Uw Marktspecialist",
    sourceUrl: "https://uwmarktspecialist.nl/markten/markt/almelo/weekmarkt/zaterdag/centrumplein-2/",
    language: "nl",
  },
  {
    id: "weekmarkt-oldenzaal",
    title: "Weekmarkt Oldenzaal",
    blurb: "Two weekly markets — Monday spread across three streets in the center, Saturday concentrated on the Markt. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Oldenzaal",
    country: "NL",
    kind: "recurring",
    recurrence: "Mon 12:00–17:00 (Ganzenmarkt/Kerkstraat/Markt) & Sat 09:00–17:00 (Markt)",
    repeatWeekdays: ["mon", "sat"],
    cost: "free",
    location: "Markt, Oldenzaal",
    sourceName: "Uw Marktspecialist",
    sourceUrl: "https://uwmarktspecialist.nl/markten/markt/oldenzaal/weekmarkt/zaterdag/markt-35/",
    language: "nl",
  },
  {
    id: "weekmarkt-losser",
    title: "Weekmarkt Losser",
    blurb: "Town-center general market. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Losser",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Thursday, 10:00–16:00",
    repeatWeekdays: ["thu"],
    cost: "free",
    location: "Raadhuisplein, Losser",
    sourceName: "VisitOost",
    sourceUrl: "https://www.visitoost.nl/agenda/losser/markt/",
    language: "nl",
  },
  {
    id: "weekmarkt-haaksbergen",
    title: "Weekmarkt Haaksbergen",
    blurb: "Morning-only town market. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Haaksbergen",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Wednesday, 08:30–12:30",
    repeatWeekdays: ["wed"],
    cost: "free",
    location: "Markt, Haaksbergen",
    sourceName: "markten.nl",
    sourceUrl: "https://markten.nl/en/weekly-market/haaksbergen/",
    language: "nl",
  },
  {
    id: "weekmarkt-borne",
    title: "Weekmarkt Borne",
    blurb: "Fashion, deli, cheese, produce, flowers and fish. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Borne",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Wednesday, 07:00–13:00",
    repeatWeekdays: ["wed"],
    cost: "free",
    location: "Marktplein / De Bolkshoek, Borne",
    sourceName: "Uw Marktspecialist",
    sourceUrl: "https://uwmarktspecialist.nl/markten/markt/borne/weekmarkt/woensdag/marktplein-de-bolkshoek/",
    language: "nl",
  },
  {
    id: "weekmarkt-delden",
    title: "Weekmarkt Delden",
    blurb: "Afternoon market: meat, fish, cheese, produce, flowers and clothing. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["afternoon", "evening"],
    city: "Delden",
    country: "NL",
    kind: "recurring",
    recurrence: "Every Friday, 14:00–18:00",
    repeatWeekdays: ["fri"],
    cost: "free",
    location: "Ressingplein, Delden",
    sourceName: "Nieuws uit Delden",
    sourceUrl: "https://www.nieuwsuitdelden.nl/agenda/weekmarkt-elke-vrijdag-van-1400-tot-18.00-uur",
    language: "nl",
  },
  {
    id: "weekmarkt-rijssen",
    title: "Weekmarkt Rijssen",
    blurb: "A smaller Monday market spread across several streets, plus a large Saturday market with food, clothing, fabrics and shoes. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Rijssen",
    country: "NL",
    kind: "recurring",
    recurrence: "Mon 08:00–14:00 (Apr–Oct) / 08:00–13:00 (Nov–Mar), closed public holidays; Sat 08:00–17:00",
    repeatWeekdays: ["mon", "sat"],
    cost: "free",
    location: "'t Schild, Rijssen",
    sourceName: "Gemeente Rijssen-Holten",
    sourceUrl: "https://www.rijssen-holten.nl/direct-regelen/ondernemen/voor-en-door-ondernemers/weekmarkten-rijssen-holten/",
    language: "nl",
  },
  {
    id: "wochenmarkt-gronau",
    title: "Gronauer Wochenmarkt",
    blurb: "Main town-center weekly market. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Gronau",
    country: "DE",
    kind: "recurring",
    recurrence: "Wed & Sat, 08:00–13:00",
    repeatWeekdays: ["wed", "sat"],
    cost: "free",
    location: "Neustraße, Gronau",
    sourceName: "Ortsdienst.de",
    sourceUrl: "https://www.ortsdienst.de/nordrhein-westfalen/borken/gronau-westfalen/wochenmarkt/",
    language: "de",
  },
  {
    id: "wochenmarkt-epe-gronau",
    title: "Eper Wochenmarkt",
    blurb: "Smaller weekly market in Gronau's Epe district. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Gronau",
    country: "DE",
    kind: "recurring",
    recurrence: "Every Friday, 08:00–13:00",
    repeatWeekdays: ["fri"],
    cost: "free",
    location: "Merschstraße, Gronau (Epe)",
    sourceName: "Ortsdienst.de",
    sourceUrl: "https://www.ortsdienst.de/nordrhein-westfalen/borken/gronau-westfalen/wochenmarkt/",
    language: "de",
  },
  {
    id: "wochenmarkt-ochtrup",
    title: "Wochenmarkt Ochtrup",
    blurb: "Fruit, veg, flowers, fish, honey, spices and meat. Timing from a secondary source, not confirmed municipally — worth double-checking. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Ochtrup",
    country: "DE",
    kind: "recurring",
    recurrence: "Every Thursday, 09:00–13:00 (unconfirmed — check locally)",
    repeatWeekdays: ["thu"],
    cost: "free",
    location: "Pottbäckerplatz, Ochtrup",
    sourceName: "alleantworten.de",
    sourceUrl: "https://alleantworten.de/wann-ist-wochenmarkt-in-ochtrup",
    language: "de",
  },
  {
    id: "wochenmarkt-nordhorn",
    title: "Nordhorner Wochenmarkt",
    blurb: "Recently moved to Neumarkt from Platz am Markt due to harbor-area construction — worth re-checking closer to visiting. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Nordhorn",
    country: "DE",
    kind: "recurring",
    recurrence: "Wed & Sat, 07:00–13:00",
    repeatWeekdays: ["wed", "sat"],
    cost: "free",
    location: "Neumarkt, Nordhorn",
    sourceName: "Stadt Nordhorn",
    sourceUrl: "https://www.nordhorn.de/portal/seiten/wochenmarkt-900000743-26710.html",
    language: "de",
  },
  {
    id: "wochenmarkt-bad-bentheim",
    title: "Wochenmarkt Bad Bentheim",
    blurb: "Weekly market (one source names Schlosspark instead of Marktplatz — worth confirming locally). Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["afternoon", "evening"],
    city: "Bad Bentheim",
    country: "DE",
    kind: "recurring",
    recurrence: "Every Friday, 14:00–18:00",
    repeatWeekdays: ["fri"],
    cost: "free",
    location: "Marktplatz, Bad Bentheim",
    sourceName: "Ortsdienst.de",
    sourceUrl: "https://www.ortsdienst.de/niedersachsen/grafschaft-bentheim/bad-bentheim/wochenmarkt/",
    language: "de",
  },
  {
    id: "wochenmarkt-rheine-marktplatz",
    title: "Wochenmarkt Rheine (Marktplatz)",
    blurb: "Rheine's main, largest weekly market. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning"],
    city: "Rheine",
    country: "DE",
    kind: "recurring",
    recurrence: "Tue, Thu & Sat, 08:00–13:00",
    repeatWeekdays: ["tue", "thu", "sat"],
    cost: "free",
    location: "Marktplatz, Rheine",
    sourceName: "Ortsdienst.de",
    sourceUrl: "https://www.ortsdienst.de/nordrhein-westfalen/steinfurt/rheine/wochenmarkt/",
    language: "de",
  },
  {
    id: "wochenmarkt-rheine-emstorplatz",
    title: "Wochenmarkt Rheine (Emstorplatz)",
    blurb: "Secondary neighborhood market. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["afternoon", "evening"],
    city: "Rheine",
    country: "DE",
    kind: "recurring",
    recurrence: "Every Friday, 14:00–18:00",
    repeatWeekdays: ["fri"],
    cost: "free",
    location: "Emstorplatz, Rheine",
    sourceName: "Ortsdienst.de",
    sourceUrl: "https://www.ortsdienst.de/nordrhein-westfalen/steinfurt/rheine/wochenmarkt/",
    language: "de",
  },
  {
    id: "wochenmarkt-rheine-mesum",
    title: "Wochenmarkt Rheine-Mesum",
    blurb: "Neighborhood market in the Mesum district. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["afternoon", "evening"],
    city: "Rheine",
    country: "DE",
    kind: "recurring",
    recurrence: "Every Thursday, 14:00–18:00",
    repeatWeekdays: ["thu"],
    cost: "free",
    location: "Alte-Bahnhof-Straße, Rheine-Mesum",
    sourceName: "Ortsdienst.de",
    sourceUrl: "https://www.ortsdienst.de/nordrhein-westfalen/steinfurt/rheine/wochenmarkt/",
    language: "de",
  },
  {
    id: "wochenmarkt-domplatz-munster",
    title: "Wochenmarkt Domplatz",
    blurb: "Münster's largest weekly market, ~150 stalls. Family-friendly: yes.",
    category: "markets",
    familyFriendly: "yes",
    timeOfDay: ["morning", "afternoon"],
    city: "Münster",
    country: "DE",
    kind: "recurring",
    recurrence: "Wed & Sat, 07:00–14:30",
    repeatWeekdays: ["wed", "sat"],
    cost: "free",
    location: "Domplatz, Münster",
    sourceName: "Dein Münster",
    sourceUrl: "https://www.dein-ms.de/veranstaltungen/eventc88ff11ac0a32e0205d4a62c4b9baa4b",
    language: "de",
  },

  // ---- Oktoberfests within a few hours (researched Sept 27, 2026) ----
  {
    id: "jetzt-gehts-losser-2026",
    title: "Jetzt Geht's Losser (Oktoberfest)",
    blurb:
      "Losser's Oktoberfest, now on Martinusplein alongside the kermis. Fri 19:30–01:00 party (18+, €12.50); Sat 15:00–19:00 seated \"Traditzional\" with half chicken (25+, €25) and 20:00–01:00 party (21+, €15); Sun 14:00–21:00 Bockbier afternoon, free, all ages. Family-friendly: Sunday only.",
    category: "seasonal",
    familyFriendly: "partly",
    timeOfDay: ["afternoon", "evening"],
    city: "Losser",
    country: "NL",
    kind: "dated",
    date: "2026-10-02",
    endDate: "2026-10-04",
    cost: "10to25",
    location: "Martinusplein, Losser",
    sourceName: "Jetzt Geht's Losser",
    sourceUrl: "https://jetztgehts-losser.nl/",
    language: "nl",
  },
  {
    id: "oktoberfest-hengelo-2026",
    title: "Oktoberfest Hengelo",
    blurb: "Beer, music and Bavarian food for one evening, with proceeds going to a local care farm. Not family-friendly: late-night adult party (no age policy published).",
    category: "seasonal",
    familyFriendly: "no",
    timeOfDay: ["evening"],
    startTime: "20:00",
    endTime: "00:30",
    city: "Hengelo",
    country: "NL",
    kind: "dated",
    date: "2026-10-16",
    cost: "10to25",
    location: "Wapen van Hengelo",
    sourceName: "Oktoberfest Hengelo",
    sourceUrl: "https://oktoberfesthengelo.nl/",
    language: "nl",
  },
  {
    id: "gronauer-oktoberfest-2026",
    title: "Gronauer Oktoberfest",
    blurb: "Two nights in a big festival tent, billed as the region's largest and most authentic. Just over the border. Not family-friendly: evening tent party from 18:00 (age policy not published).",
    category: "seasonal",
    familyFriendly: "no",
    timeOfDay: ["evening"],
    city: "Gronau",
    country: "DE",
    kind: "dated",
    date: "2026-10-23",
    endDate: "2026-10-24",
    cost: "10to25",
    location: "Festplatz Bürgerhalle, Spinnereistraße 20, Gronau",
    sourceName: "Gronauer Oktoberfest",
    sourceUrl: "https://gronauer-oktoberfest.de/",
    language: "de",
  },
  {
    id: "oktoberfest-munster-2026",
    title: "Oktoberfest Münster",
    blurb:
      "4,500-person festival tent near the harbour with a small fair and umbrella bar. Open select evenings (mostly Fri/Sat) through Oct 10, 17:30–midnight. Standing tickets €18, cashless only. ~50 min away. Not family-friendly: 18+ only, no exceptions with a parent.",
    category: "seasonal",
    familyFriendly: "no",
    timeOfDay: ["evening"],
    startTime: "17:30",
    endTime: "00:00",
    city: "Münster",
    country: "DE",
    kind: "dated",
    date: "2026-09-25",
    endDate: "2026-10-10",
    cost: "10to25",
    pricePerPerson: 19,
    location: "Albersloher Weg 58, Münster",
    sourceName: "Oktoberfest Münster",
    sourceUrl: "https://www.oktoberfest-muenster.de/en/",
    language: "de",
  },
  {
    id: "matrixx-oktoberfest-2026",
    title: "Matrixx Oktoberfest",
    blurb:
      "Large outdoor Oktoberfest festival with 20+ acts across 3 areas: a beer tent, a Schlager tent and food stalls. Last entry 21:00. 15 min walk from Arnhem Zuid station, ~1h15 away. Not family-friendly: 18+ only.",
    category: "seasonal",
    familyFriendly: "no",
    timeOfDay: ["afternoon", "evening"],
    startTime: "14:00",
    endTime: "23:00",
    city: "Elst (Arnhem)",
    country: "NL",
    kind: "dated",
    date: "2026-10-10",
    cost: "25to50",
    location: "Park Lingezegen, Elst",
    sourceName: "Matrixx Oktoberfest",
    sourceUrl: "https://matrixxoktoberfest.nl/",
    language: "nl",
  },
  {
    id: "oktoberfest-dortmund-2026",
    title: "Das Dortmunder Oktoberfest",
    blurb:
      "Heated 4,000-person Bavarian tent with Schlager acts such as Mickie Krause and Lorenz Büffel. Festbier and Bavarian food. Strict dress code: Tracht required (dirndl/lederhosen; no T-shirts or carnival costumes). Seats held only for arrivals 16:30–19:30. ~1h45 away. Not family-friendly: 18+ only.",
    category: "seasonal",
    familyFriendly: "no",
    timeOfDay: ["evening"],
    city: "Dortmund",
    country: "DE",
    kind: "recurring",
    recurrence: "Fri & Sat evenings: Oct 2–3 and Oct 16–17, 2026",
    repeatDates: ["2026-10-02", "2026-10-03", "2026-10-16", "2026-10-17"],
    cost: "25to50",
    location: "Revierpark Wischlingen, Dortmund",
    sourceName: "Das Dortmunder Oktoberfest",
    sourceUrl: "https://www.das-dortmunder-oktoberfest.de",
    language: "de",
  },
  {
    id: "oktoberfest-lingen-2026",
    title: "Oktoberfest Lingen",
    blurb:
      "Emsland's biggest Bavarian party, 2,000+ guests in the Emslandhallen, with live music, party hits and freshly tapped beer. ~50 min away. Not family-friendly: evening party (age policy not published).",
    category: "seasonal",
    familyFriendly: "no",
    timeOfDay: ["evening"],
    city: "Lingen",
    country: "DE",
    kind: "dated",
    date: "2026-10-10",
    cost: "10to25",
    location: "Emslandhallen, Lingen",
    sourceName: "Oktoberfest Lingen",
    sourceUrl: "https://www.oktoberfest-lingen.de/",
    language: "de",
  },
  {
    id: "oktoberfest-osnabrueck-2026",
    title: "Oktoberfest Osnabrück",
    blurb:
      "Two nights for up to 2,500 guests in the Halle Gartlage, with Paulaner beer, sausages, roast pork and pretzels, and the bands Partyräuber and Die PartyHirschen. ~1h away. Not family-friendly: evening party (age policy not published).",
    category: "seasonal",
    familyFriendly: "no",
    timeOfDay: ["evening"],
    city: "Osnabrück",
    country: "DE",
    kind: "dated",
    date: "2026-10-02",
    endDate: "2026-10-03",
    cost: "25to50",
    location: "Halle Gartlage, Schlachthofstraße 48, Osnabrück",
    sourceName: "Halle Gartlage",
    sourceUrl: "https://www.hallegartlage.de/oktoberfest2026/",
    language: "de",
  },
  {
    id: "bochum-oktoberfest-2026",
    title: "Bochum Oktoberfest",
    blurb:
      "Two-day Wiesn party (5th edition) with the Würzbuam and Frankenbengel bands plus Schlager acts such as Lorenz Büffel, Olaf Henning and Anna-Maria Zimmermann. ~1h45 away. Not family-friendly: adult party (age policy not published).",
    category: "seasonal",
    familyFriendly: "no",
    timeOfDay: ["afternoon", "evening"],
    startTime: "15:30",
    endTime: "23:00",
    city: "Bochum",
    country: "DE",
    kind: "dated",
    date: "2026-10-16",
    endDate: "2026-10-17",
    cost: "25to50",
    location: "Glas Strack, Ottostraße 2–4, Bochum",
    sourceName: "Bochum Oktoberfest",
    sourceUrl: "https://www.bochum-oktoberfest.de/",
    language: "de",
  },
  {
    id: "bielefelder-oktoberfest-2026",
    title: "Bielefelder Oktoberfest",
    blurb:
      "Ostwestfalen's biggest Wiesn party (27th edition) with the Münchner Zwietracht band and Bavarian food. Booked as 8-person tables (~€94–€212 per table, local transit included), dirndl and lederhosen encouraged. ~1h45 away. Not family-friendly: 18+ only.",
    category: "seasonal",
    familyFriendly: "no",
    timeOfDay: ["evening"],
    city: "Bielefeld",
    country: "DE",
    kind: "dated",
    date: "2026-10-30",
    endDate: "2026-10-31",
    cost: "10to25",
    location: "Seidensticker Halle, Stadtholz 24-26, Bielefeld",
    sourceName: "Bielefelder Oktoberfest",
    sourceUrl: "https://www.bielefelder-oktoberfest.de/",
    language: "de",
  },
  {
    id: "oktoberfest-hannover-2026",
    title: "Oktoberfest Hannover",
    blurb:
      "One of northern Germany's biggest Oktoberfests: two festival halls plus a full fair with rides. Free entry. Wed–Thu 15:00–23:00, Fri–Sat 15:00–midnight, Sun 14:00–23:00, closed Mon–Tue. Fireworks at 21:45 on Oct 2 and Oct 9, plus a lantern parade Oct 9. ~2h15 away. Family-friendly: Wednesday family days with up to 50% off rides.",
    category: "seasonal",
    familyFriendly: "yes",
    timeOfDay: ["afternoon", "evening"],
    city: "Hannover",
    country: "DE",
    kind: "dated",
    date: "2026-09-25",
    endDate: "2026-10-11",
    cost: "free",
    location: "Schützenplatz, Bruchmeisterallee 1A, Hannover",
    sourceName: "Visit Hannover",
    sourceUrl: "https://www.visit-hannover.com/en/Event-Highlights,-Kultur-Freizeit/Top-Events-und-Veranstaltungen/Feste-und-Spezial/Oktoberfest-2026",
    language: "en",
  },
  {
    id: "bayernfesthalle-freimarkt-bremen-2026",
    title: "Bayernfesthalle at the Bremer Freimarkt",
    blurb:
      "Bavarian festival hall with daily events (morning sessions, Alpine parties) inside the Freimarkt, one of Germany's oldest and biggest funfairs. Free to enter the fair; hall tables are reserved separately. ~2h15 away. Family-friendly: the fair is great for kids; the festival hall parties are for adults.",
    category: "seasonal",
    familyFriendly: "partly",
    city: "Bremen",
    country: "DE",
    kind: "dated",
    date: "2026-10-16",
    endDate: "2026-11-01",
    cost: "free",
    location: "Bürgerweide, Bremen",
    sourceName: "Weser-Kurier",
    sourceUrl: "https://www.weser-kurier.de/bremen/mit-mass-hier-koennen-oktoberfest-fans-2026-in-bremen-feiern-doc87pkb5s9nt418cck572",
    language: "de",
  },
  {
    id: "oktoberfeest-sittard-2026",
    title: "Oktoberfeest Sittard",
    blurb:
      "The largest Oktoberfest in the Netherlands: six days with five party tents, an Almdorf of German huts, a fair and parades. Walkable from Sittard station. Most evenings are ticketed, and Sunday's Limburgse Middig is free. ~2h45 away. Family-friendly by day: the fair, parades and free Sunday afternoon suit kids; the evening tent parties are for adults.",
    category: "seasonal",
    familyFriendly: "partly",
    city: "Sittard",
    country: "NL",
    kind: "dated",
    date: "2026-10-16",
    endDate: "2026-10-21",
    cost: "10to25",
    location: "Schootsvelden, Sittard",
    sourceName: "Oktoberfeest Sittard",
    sourceUrl: "https://oktoberfeestsittard.nl/",
    language: "nl",
  },
];
